---
id: oddmuse6
name: Oddmuse 6
links:  []
entrypoint: service.p6
cro: 1
ignore:
  - resources/
  - wiki/
env:
  - name: ODDMUSE_IMAGES
    value: resources/images
  - name: ODDMUSE_CSS
    value: resources/css
  - name: ODDMUSE_TEMPLATES
    value: resources/templates
  - name: ODDMUSE_WIKI
    value: wiki
  - name: ODDMUSE_STORAGE
    value: Oddmuse::Storage::File
  - name: ODDMUSE_MENU
    value: Home, Changes, About
  - name: ODDMUSE_CHANGES
    value: Changes
  - name: ODDMUSE_QUESTION
    value: Do you prefer cats or dogs?
  - name: ODDMUSE_ANSWER
    value: cat, cats, dog, dogs, bird, birds
  - name: ODDMUSE_SECRET
    value: This-is-a-secret.
endpoints: 
  - 
    id: http
    name: HTTP
    protocol: http
    host-env: ODDMUSE_HOST
    port-env: ODDMUSE_PORT
...