---
id: edit
links:  []
entrypoint: service.p6
cro: 1
env:
  - name: dir
    value: .
  - name: storage
    value: Storage::File
name: edit
endpoints: 
  - 
    host-env: EDIT_HOST
    id: http
    port-env: EDIT_PORT
    protocol: http
    name: HTTP
...