---
id: oddmuse6
links:  []
entrypoint: service.p6
cro: 1
env:
  - name: images
    value: images
  - name: css
    value: css
  - name: templates
    value: templates
  - name: wiki
    value: wiki
  - name: storage
    value: Storage::File
  - name: menu
    value: Home, Changes, About
  - name: changes
    value: Changes
name: edit
endpoints: 
  - 
    host-env: EDIT_HOST
    id: http
    port-env: EDIT_PORT
    protocol: http
    name: HTTP
...