---
id: oddmuse6
name: Oddmuse 6
links:  []
entrypoint: service.p6
cro: 1
ignore:
  - resources/
env:
  - name: images
    value: resources/images
  - name: css
    value: resources/css
  - name: templates
    value: resources/templates
  - name: wiki
    value: ../wiki
  - name: storage
    value: Oddmuse::Storage::File
  - name: menu
    value: Home, Changes, About
  - name: changes
    value: Changes
endpoints: 
  - 
    id: http
    name: HTTP
    protocol: http
    host-env: ODDMUSE_HOST
    port-env: ODDMUSE_PORT
...